### ISSUE TITLE
Character->Relationships->New Relationship loses mouse-focus on dropdown when over fixed field

### ISSUE THREAD

**Issue by SeanFager** [storybuilder-org/StoryCAD#568] opened 2023-05-25 19:56 UTC
**Describe the bug**
While using the "Create a New Relationship" pop-up the two dropdowns for selecting the relationship status between the current node Character and another node Character function as expected except when the mouse hovers over the field selected to open the dropdown (which is behind the dropdown list). See images.

<details>
  <summary>Images</summary>
  
<img width="807" alt="DropdownsClosed" src="https://github.com/storybuilder-org/StoryCAD/assets/120670213/c2aad152-2ac1-4eb1-a7e4-3ddefd902f2f">
<img width="777" alt="DropdownBlock" src="https://github.com/storybuilder-org/StoryCAD/assets/120670213/dc2e02cd-09a2-4b4e-8dd7-a8397e5a1860">
<img width="777" alt="DropdownBlock2" src="https://github.com/storybuilder-org/StoryCAD/assets/120670213/3a9b80c3-f5c3-48e6-9209-0923f6f49ce2">

</details>

**To Reproduce**
1. Go to a Character entry (or create one).
2. Click on "Relationships" under the Character Name field.
3. Click on "Create a new relationship"
4. Click on the blank field between "[Character name] is a" and "to [empty field]"
5. Move the mouse around the screen, and then back to a position over the field you clicked in the previous step (now obscured by the dropdown).
6. Attempt to select the entry presented at that point ("Business Acquaintance" at my screen resolution, but yours may differ)
_Error occurs here, as option cannot be selected, mouse appears to be focused on hidden field rather than dropdown menu._
7. Select another option, or click outside dropdown to collapse it.
8. Check the box for "Make a relationship on the other character"
9. Click on the blank field "is a [FIELD] to [Character name]"
10. Repeat steps 5 and 6 for the new dropdown. 

**Expected behavior**
The entries "over" the selected field should still be available for selection. 

**Screenshots**
See expandable field above.

**Additional context**
Doesn't occur between fields (the mouse doesn't 'lose focus' over the field NOT selected to initiate the dropdown) or in the Flaw Builder / other Character node pop-up field-selection-activated dropdowns.

**Comment by Rarisma** [comment] 2023-05-27 16:14
Cannot replicate @SeanFager, can you please attach a recording of this bug or email me one if you can.

**Comment by SeanFager** [comment] 2023-05-28 12:47
[MouseFocus.zip](https://github.com/storybuilder-org/StoryCAD/files/11584584/MouseFocus.zip)

Attached.  Sorry for the *.zip, it looks like github won't do *.mkv uploads in this context.

**Comment by terrycox** [comment] 2023-05-29 11:58
I'm not sure I understand the issue Sean's reporting. However, there is an issue I do follow, which is that after you've entered the other character name, the rest of the relationship (Trait, Attitude, and Notes) doesn't show until you mouse over the Protagonist field. I'm attaching an image which describes this.
![Problem with Relationship Mouseover](https://github.com/storybuilder-org/StoryCAD/assets/5607778/e352b977-a143-46db-937d-66da845acffc)

**Comment by Rarisma** [comment] 2023-06-02 15:38
This seems to be a WinUI bug, not a bug caused directly by storybuilder, I will report this to them on a future date.
This can and will be fixed due the comboboxes also cutting off by switching them to sf comboboxes. (see issue #518)

**Comment by terrycox** [comment] 2023-06-27 22:00
WIth the combobox converted to SFComboBox, the new Relationship can be entered. However, the editable sfcombobox of relationship types doesn't drop down.

This has been reported to SyncFusion and they reported the following:

A new update has been posted in your ticket, #[471146](https://support.syncfusion.com/support/tickets/471146). Karthick Arjunan has added the following comment.

Terry Cox,
We have confirmed the reported scenario is a defect and logged a report for the reported scenario "While using SfComboBox in a ContentDialog, it doesn't display the list of strings when clicking down arrow”. We will provide the fix in the upcoming weekly NuGet release which is expected to roll out on 11th July 2023.
You can track the status of this defect using the following feedback link: [https://www.syncfusion.com/feedback/44577/while-using-sfcombobox-in-a-contentdialog-it-doesnt-display-the-list-of-strings ](https://www.syncfusion.com/feedback/44577/while-using-sfcombobox-in-a-contentdialog-it-doesnt-display-the-list-of-strings)
 
If you have any more specification replication procedures or a scenario to be tested, you can add it as a comment in the portal.

Please let us know if you need any further assistance.


Regards,
Karthick Arjunan

**Comment by Rarisma** [comment] 2023-07-10 18:25
This was not rolled out by SF and should actually be fixed by them in a release aimed around september unfortunetly.

**Comment by Rarisma** [comment] 2023-07-13 19:32
Update I'm wrong, and this package has released within the previous few days as far as I am aware
This issue will addressed within a comming PR and will be fixed within the next release of StoryCAD.

**Comment by Rarisma** [comment] 2023-07-14 18:45
Fixed in #601

**Closed by Rarisma** 2023-07-14 18:45 UTC
Labels: bug
